### PR TITLE
Node18upgrade

### PR DESCRIPTION
**Pull request by jcwatson11**

### CODE REVIEW

**Comment by jcwatson11** [comment]
@Omicron7 This one says a review is required by someone. Not sure who. So I added you. If you know a better reviewer, please let me know.

**Comment by jcwatson11** [comment]
@Omicron7 Is it okay to just skip the review on this and merge?

**Comment by Omicron7** [comment]
@wrandall22 This project still in use? README says it sends/receives data from BigQuery which we haven't used in a while.

**Comment by wrandall22** [comment]
Yes, it is still in use.

**Review by Omicron7 — APPROVED** [review]

**Review by dr-bizz — APPROVED** [review]
Looks good. Testing on local with node18.

I also tested on node20 (it worked!). I know Lambda doesn't support node20 yet, but I'm just documenting it here for future devs.

**Pull request merged**
